# Site settings
title: OpenStreetMap Brasil
email: vitor.george@openstreetmap.com.br
description: "Informações sobre como mapear, usar dados e participar da comunidade do OpenStreetMap."
baseurl: ""
url: "http://www.openstreetmap.com.br"
twitter_username: mapaslivres
github_username:  OSMBrasil

# Build settings
markdown: kramdown
permalink: pretty
