# Site settings
title: OpenStreetMap Brasil
email: 
description: "Associação de mapeadores"
baseurl: ""
url: "http://www.openstreetmap.com.br"
twitter_username: 
github_username:  OSMBrasil

# Build settings
markdown: kramdown
permalink: pretty

# Plugin settings
gems:
  - jekyll-sitemap
